import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UsersPage from "./users/page";
import CardSkill from "./components/card-skill";
import ProfileDesc from "./components/profile-desc";
import UsedLinks from "./components/used-links";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className=" my-4 mx-4">{children}</main>
      </body>
    </html>
  );
}
